### ISSUE TITLE
userChrome.css?

### ISSUE THREAD

**Issue by AcarBurak** [QupZilla/qupzilla#2581]
Since version 2.2.4 we have this. Any pointer about how to use, implement it?

**Comment by cranes-bill** [comment]
It's just in addition to current theme. It also overrides the already defined elements. For example, save the following in the current profile directory and see what's going on:
<details>
<summary>UserChrome.css</summary>

``` css
#mainwindow
{
    background : green;
}
BookmarksToolbarButton, 
#navigation-button-back,
#navigation-button-next,
#navigation-button-stop,
#navigation-button-reload,
#navigation-button-home,
#navigation-button-addtab,
#navigation-button-tools,
#navigation-button-exitfullscreen,
#navigation-button-supermenu,
#navigationbar ToolButton[toolbar-look="true"]
{
     background-color: red;
     border-style: solid;
     border-radius: 2px;
     border-width: 1px;
     border-color: white;
     padding: 4px;
     margin: 1px;
}
```
</details>

More, how to style themes [here](https://github.com/QupZilla/qupzilla/wiki/Themes)
